const CATALOG_ITEMS = [
    {
        id: 1 ,
        titulo: "Coraline",
        categorias: "Livros",
        detalhes: "No livro Coraline, de Neil Gaiman, a jovem Coraline se muda com os pais para um antigo casarão e descobre uma porta que a leva a um mundo paralelo idêntico ao seu, mas mais perfeito.",
        preco: "R$:40,90",
        estoque: 35,
        autor: "Neil Galman",
        lancamento: "02/07/2002",
    },
        {
        id: 2 ,
        titulo: "Raposa de crochê",
        categorias: "Artesanato",
        detalhes: "Um bichinho de pelucia de raposa com aproximadamente 30cm",
        preco: "R$25,50",
        estoque: 10,
        material: "Lã de cor laranja e algodão por dentro",
        dimensoes: "30cm x 15cm",
    },
        {
        id: 3 ,
        titulo: "A Bilioteca da Meia Noite",
        categorias: "Livros",
        detalhes: "A Biblioteca da Meia-Noite é um romance de Matt Haig sobre Nora Seed, uma mulher de 35 anos que, arrependida de suas escolhas, tenta suicídio e se encontra em uma biblioteca mágica entre a vida e a morte.",
        preco: "R$40,82",
        estoque: 49,
        autor: "Matt Haig",
        lancamento: "13/08/2020",
    },
        {
        id: 4,
        titulo: "Bolsa de crochê - Hello kitty",
        categorias: "Artesanato",
        detalhes: "Bolsa adulto/infantil Sanrio Hello Kitty",
        preco: "R$50,00",
        estoque: 29,
        material: "Lã colorida",
        tamanho: "Médio/Grande",
    },
]